version: '3.8'

services:
    web:
        build:
            context: .
            target: web
        env_file:
            - .env
        ports:
            - "8080:80"  # Apache'nin 80 portunu 8080 portuna yönlendirin
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        entrypoint: sh -c "sleep 25 && php /var/www/html/artisan key:generate && php /var/www/html/artisan migrate --force && php /var/www/html/artisan app:task-create && apache2-foreground"


    db:
        image: mysql:5.7
        platform: "linux/amd64"
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: task-management
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mydatabase:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "--silent"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s

volumes:
    mydatabase:
